FROM node:22-alpine AS build

# Working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the application code
COPY . .

# Build the application
RUN npm run build
RUN npx prisma generate

# Production Stage
FROM node:22-alpine AS production

# Working directory inside the container
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/prisma.config.ts ./
COPY package*.json ./

# Start the application
CMD ["npm", "run", "start:prod"]
