// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { readEnvOrFile } from './src/common/env.js';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    seed: 'tsx ./prisma/seed.ts',
    path: 'prisma/migrations',
  },
  datasource: {
    url: readEnvOrFile('DATABASE_URL'),
  },
});
